### PR TITLE
Fix for jshooks at macos build

### PR DESCRIPTION
**Pull request by tequdev**
### Type of Change

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Refactor (non-breaking change that only restructures code)
- [ ] Tests (you added tests for code that already exists, or your new feature included in this PR)
- [ ] Documentation update
- [ ] Chore (no impact to binary, e.g. `.gitignore`, formatting, dropping support for older tooling)
- [ ] Release

### API Impact

- [ ] Public API: New feature (new methods and/or new fields)
- [ ] Public API: Breaking change (in general, breaking changes should only impact the next api_version)
- [ ] `libxrpl` change (any change that may affect `libxrpl` or dependents of `libxrpl`)
- [ ] Peer protocol change (must be backward compatible or bump the peer protocol version)

### CODE REVIEW

**Comment by dangell7** [comment]
This could also be done with an else if operation. Apple has added this to clang 17 so we are just waiting. Or I'm also fine with commenting out until then

**Comment by RichardAH** [comment]
yeah can we do this with preprocessor macros so we don't revert to the much slower implementation of the space ship operator if we don't need to?
```
#ifdef __APPLE__
    // macOS-specific code here
#elif
   // existing code
#endif
```

**Comment by tequdev** [comment]
Since the problem with the base_unit.h file is not only in the jshooks branch but also in the dev branch, it may be better to create a separate PR?

**Comment by dangell7** [comment]
> Since the problem with the base_unit.h file is not only in the jshooks branch but also in the dev branch, it may be better to create a separate PR?

Yes I would suggest that

**Comment by tequdev** [comment]
#391

**Comment by RichardAH** [comment]
i'll back merge dev into jshooks so I don't think this is needed anymore?

**Comment by tequdev** [comment]
> i'll back merge dev into jshooks so I don't think this is needed anymore?

Only the `ripple/json/json_reader.h` include fix remains, but it can do either in this PR or directly in the jshook branch.

**Pull request merged**
